### ISSUE TITLE
Also it combines weather and air quality. Given that there is an ad hoc env monitoring model, shouldn't the two be kept separate?

### ISSUE THREAD

**Issue by chicco785** [smart-data-models/dataModel.Weather#17]
https://github.com/smart-data-models/dataModel.Weather/blob/de19ea6b9797a72fd36fc1313d9b98de63c893b7/WeatherObserved/schema.json#L127

**Comment by albertoabellagarcia** [comment]
In many cities 'weather' is understood also as the environmental quality of the air. That's why is there (and of course because there is a use case supporting it).
But having an attribute here does not restrict to having it in other data models (only that if they are the same, they have to share the data type).
Besides this, if this attribute is not relevant to you, you can skip it. Few (the fewer the better) attributes are mandatory.

**Comment by albertoabellagarcia** [comment]
And thanks for the question
