### ISSUE TITLE
Attributes were removed from context

### ISSUE THREAD

**Issue by gasserluc** [smart-data-models/dataModel.Weather#20]
Is there a reason on why those attribute were removed from the context: https://github.com/smart-data-models/dataModel.Weather/commit/9ac1f189f386387fced6b937eb175e5d12088aa7 ? or is it an error ?

**Comment by bobeal** [comment]
Hi,

Indeed, this is a major thing as it breaks a lot of our use-cases that are using this context. Removing a term from a context is a breaking change (expansion / compaction no longer works as expected). 

Is there an option to add them back? Or do we have to use our own weather data model since we need those terms?

**Comment by albertoabellagarcia** [comment]
This has to be an error in the new process for creating the context. We'll check this out.
Thanks for reporting

**Comment by JilinHe** [comment]
Now all the attributes in context are back. Thank you.
